name: E2E Tests

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  cypress:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        core:
          - {name: 'WP latest', version: 'latest'}
          - {name: 'WP minimum', version: 'WordPress/WordPress#5.7'}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm i

    - name: Install composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Build asset
      run: npm run build

    - name: Set the core version
      run: ./tests/bin/set-core-version.js ${{ matrix.core.version }}

    - name: Set up WP environment
      run: npm run wp-env start

    - name: Test
      run: npm run cypress:run
    - name: Update summary
      run: |
        npx mochawesome-merge ./tests/cypress/reports/*.json -o tests/cypress/reports/mochawesome.json
        rm -rf ./tests/cypress/reports/mochawesome-*.json
        npx mochawesome-json-to-md -p ./tests/cypress/reports/mochawesome.json -o ./tests/cypress/reports/mochawesome.md
        npx mochawesome-report-generator tests/cypress/reports/mochawesome.json -o tests/cypress/reports/
        cat ./tests/cypress/reports/mochawesome.md >> $GITHUB_STEP_SUMMARY
