name: Linting

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup node v16 and npm cache
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: npm

    - name: Install Node dependencies
      run: npm ci --no-optional

    - name: Get updated JS files
      id: changed-files
      uses: tj-actions/changed-files@v42
      with:
        files: |
          **/*.js

    - name: Run JS linting
      if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
      run: ./node_modules/.bin/10up-toolkit lint-js ${{ steps.changed-files.outputs.all_changed_files }}
